"""initial

Revision ID: 01
Revises: 
Create Date: 2025-06-23 11:25:09.837024

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '01'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

languages_data = [
    {"name": "Українська", "code": "uk"},
    {"name": "English", "code": "en"},
]

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    languages_table = op.create_table('languages',
    sa.Column('language_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=55), nullable=False),
    sa.Column('code', sa.String(length=55), nullable=False),
    sa.PrimaryKeyConstraint('language_id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('users',
    sa.Column('user_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('username', sa.String(length=128), nullable=True),
    sa.Column('full_name', sa.String(length=128), nullable=False),
    sa.Column('language_id', sa.Integer(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['language_id'], ['languages.language_id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )

    op.bulk_insert(
        languages_table,
        languages_data,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('languages')
    # ### end Alembic commands ###
